version: '3.8'

services:
  flask_db:
    container_name: flask_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - flask_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
